[project]
name = "promptzip"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.12.3"
dependencies = [
    "accelerate",
    "datasets==4.2.0",
    "fuzzywuzzy>=0.18.0",
    "jieba>=0.42.1",
    "nltk>=3.9.3",
    "rouge>=1.0.1",
    "sentence-transformers>=5.2.3",
    "torch==2.7.1",
    "transformers==4.57.0",
    "vllm==0.10.0",
    "flash-attn==2.7.4.post1",
    "blingfire==0.1.8",
    "onnxruntime-gpu==1.23.2",
    "optimum==2.1.0",
    "optimum-onnx[onnxruntime-gpu]",
]

[tool.uv.extra-build-dependencies]
flash-attn = [{ requirement = "torch", match-runtime = true }]